// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_16iwYSR4COua6i-qeptpq-n3OAQnU28',
    appId: '1:723416481584:web:9c191d80918d0c42e212f5',
    messagingSenderId: '723416481584',
    projectId: 'dinnerparty-app',
    authDomain: 'dinnerparty-app-30e2a.firebaseapp.com',
    storageBucket: 'dinnerparty-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFWYvMmXbUPaoVPTpXQhK4XQllkpx0DaE',
    appId: '1:723416481584:android:418e7bfd15840d8ae212f5',
    messagingSenderId: '723416481584',
    projectId: 'dinnerparty-app',
    storageBucket: 'dinnerparty-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVl8aDtZ6n8Z57QCNJzy2W5hac2Wtpwrw',
    appId: '1:723416481584:ios:3072478ba40efea9e212f5',
    messagingSenderId: '723416481584',
    projectId: 'dinnerparty-app',
    storageBucket: 'dinnerparty-app.appspot.com',
    iosBundleId: 'com.dinnerpartyapp.dinnerparty',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVl8aDtZ6n8Z57QCNJzy2W5hac2Wtpwrw',
    appId: '1:723416481584:ios:3072478ba40efea9e212f5',
    messagingSenderId: '723416481584',
    projectId: 'dinnerparty-app',
    storageBucket: 'dinnerparty-app.appspot.com',
    iosBundleId: 'com.dinnerpartyapp.dinnerparty',
  );
}
